import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ApiClient, ApiError, quoteQuality, validateSnapshot, validateContracts, formatNumber, contractLabel, ageLabel} from '../src/frontend/dashboard/model.mjs';
const c={contract_id:1,symbol:'DEMO',exchange:'SIM',currency:'USD',security_type:'STK',multiplier:1};
const quote=()=>({contract_id:1,data_type:'realtime',bid:{price:99,receipt_age_ms:20},ask:{price:101,receipt_age_ms:30}});
const state=()=>({schema_version:1,broker:{mode:'mock',state:'ready',enabled:true,read_only:true,errors:[]},subscriptions:[],positions:{status:'unavailable',positions:null}});
test('valid midpoint and spread',()=>assert.deepEqual(quoteQuality(quote()),{status:'realtime',mid:100,spread:2}));
test('missing quote is not zero',()=>assert.equal(quoteQuality(null).mid,null));
test('missing bid is unavailable',()=>{const q=quote();q.bid=null;assert.equal(quoteQuality(q).mid,null);});
test('null price is not coerced to zero',()=>{const q=quote();q.bid.price=null;assert.equal(quoteQuality(q).status,'invalid');});
test('crossed market has no midpoint',()=>{const q=quote();q.bid.price=102;assert.equal(quoteQuality(q).status,'crossed');});
test('NaN and infinity rejected',()=>{for(const bad of [NaN,Infinity,-Infinity]){const q=quote();q.ask.price=bad;assert.equal(quoteQuality(q).mid,null);}});
test('fresh ask cannot refresh stale bid',()=>{const q=quote();q.bid.receipt_age_ms=5001;assert.equal(quoteQuality(q).status,'stale');});
test('browser elapsed time ages both sides',()=>assert.equal(quoteQuality(quote(),5000).status,'stale'));
test('negative and missing timestamps rejected',()=>{for(const bad of [-1,null,undefined]){const q=quote();q.bid.receipt_age_ms=bad;assert.equal(quoteQuality(q).status,'invalid');}});
test('delayed/frozen/simulation retain type',()=>{for(const mode of ['delayed','frozen','delayed_frozen','simulation']){const q=quote();q.data_type=mode;assert.equal(quoteQuality(q).status,mode);}});
test('unavailable snapshot accepted only with null rows',()=>{assert.equal(validateSnapshot(state()).positions.positions,null);const s=state();s.positions.positions=[];assert.throws(()=>validateSnapshot(s));});
test('complete empty is distinct and requires completion time',()=>{const s=state();s.positions={status:'complete',positions:[],completed_at_unix_ms:123};assert.equal(validateSnapshot(s).positions.positions.length,0);delete s.positions.completed_at_unix_ms;assert.throws(()=>validateSnapshot(s));});
test('schema and read-only contract fail closed',()=>{for(const key of ['schema_version','broker']){const s=state();delete s[key];assert.throws(()=>validateSnapshot(s));}const s=state();s.broker.read_only=false;assert.throws(()=>validateSnapshot(s));});
test('duplicate subscriptions rejected',()=>{const s=state();s.subscriptions=[{subscription_id:1,contract:c,quote:null},{subscription_id:2,contract:c,quote:null}];assert.throws(()=>validateSnapshot(s));});
test('unknown feed rejected',()=>{const s=state();const q=quote();q.data_type='guessed';s.subscriptions=[{subscription_id:1,contract:c,quote:q}];assert.throws(()=>validateSnapshot(s));});
test('all candidates retained, no first-match selection',()=>{const data={status:'complete',contracts:[c,{...c,contract_id:2,exchange:'OTHER'}]};assert.equal(validateContracts(data).contracts.length,2);assert.throws(()=>validateContracts({...data,status:'pending'}));});
test('option identity includes expiry right strike',()=>assert.equal(contractLabel({...c,security_type:'OPT',expiry:'20261218',right:'C',strike:100}),'DEMO 20261218 C 100'));
test('format missing values without coercion',()=>{assert.equal(formatNumber(null),'—');assert.equal(formatNumber(0),'0');assert.equal(ageLabel(null),'age unknown');});
test('client confines bearer to same-origin API and never persists it',async()=>{let request;const client=new ApiClient(async(path,opts)=>{request={path,...opts};return{ok:true,json:async()=>({})};});client.setToken('local-test-secret');await client.request('/api/dashboard');assert.equal(request.headers.Authorization,'Bearer local-test-secret');assert.equal(request.redirect,'error');assert.equal(request.mode,'same-origin');assert.equal(request.credentials,'omit');assert(!request.path.includes('secret'));await assert.rejects(()=>client.request('//attacker.invalid'));await assert.rejects(()=>client.request('/api/orders',{method:'PUT'}));client.clear();await client.request('/api/dashboard');assert.equal(request.headers.Authorization,undefined);});
test('401 gives fixed error not reflected server payload',async()=>{const client=new ApiClient(async()=>({ok:false,status:401,json:async()=>({error:'secret'})}));await assert.rejects(()=>client.request('/api/dashboard'),e=>e instanceof ApiError && e.status===401 && !e.message.includes('secret'));});
test('mutation failures are not automatically retried',async()=>{let calls=0;const client=new ApiClient(async()=>{calls++;throw new Error('potential credential in upstream error');});await assert.rejects(()=>client.request('/api/broker/connect',{method:'POST'}),/not retried/);assert.equal(calls,1);});
