import test from 'node:test';
import assert from 'node:assert/strict';
import {id,replayConfig,nextCursor,validateManifest,validateReplay,validateExperiment,comparisonLabel} from '../../src/frontend/dashboard/replay-model.mjs';
const s={kind:'frozen_historical_snapshot',schema_version:1,retrospective_only:true,immutable:true,snapshot_id:'1',dataset_id:'2',bar_count:2,bar_size:'1 day',fingerprint:'a'.repeat(64),quality:{complete_market_history:false,warnings:[]}};
const c={windows:[2],annualization_factor:252};
const r={kind:'retrospective_return_diagnostics',schema_version:1,engine_version:'retrospective-replay-1',retrospective_only:true,snapshot_id:'1',snapshot_fingerprint:s.fingerprint,processed:1,total:2,complete:false,config:c,points:[{ordinal:1,coordinate_s:1767571200,available_s:null,close:100,log_return:null,rolling:[{window:2,observations:0,mean_log_return:null,annualized_volatility:null}]}]};
test('decimal string IDs',()=>{assert.equal(id('999999999999999999'),'999999999999999999');for(const x of [1,'01','0','../1','1?x=2','1'.repeat(19)])assert.throws(()=>id(x));});
test('explicit config',()=>assert.deepEqual(replayConfig('5,20',252),{windows:[5,20],annualization_factor:252}));
test('invalid/blank configuration',()=>{for(const x of ['','5,5','20,5','1','5,','NaN','2,3,4,5,6','2.5'])assert.throws(()=>replayConfig(x,252));for(const x of ['',NaN,Infinity,0,-1,1e8])assert.throws(()=>replayConfig('5',x));});
test('presentation batch cannot alter cursor domain',()=>{assert.equal(nextCursor(78,80,20),80);for(const x of [-1,81,1.5])assert.throws(()=>nextCursor(x,80,1));});
test('snapshot provenance required',()=>{assert.equal(validateManifest(s),s);for(const patch of [{retrospective_only:false},{immutable:false},{bar_count:2001},{bar_size:'unknown'},{fingerprint:'x'}])assert.throws(()=>validateManifest({...s,...patch}));});
test('matching prefix accepted',()=>assert.equal(validateReplay(r,s,c,1),r));
test('future or mismatched cursor rejected',()=>{for(const patch of [{processed:2},{snapshot_id:'5'},{snapshot_fingerprint:'b'.repeat(64)},{points:[...r.points,...r.points]},{complete:true}])assert.throws(()=>validateReplay({...r,...patch},s,c,1));});
test('wrong configuration rejected',()=>assert.throws(()=>validateReplay({...r,config:{windows:[3],annualization_factor:252}},s,c,1)));
test('daily cannot invent availability timestamps',()=>{const v=structuredClone(r);v.points[0].available_s=v.points[0].coordinate_s;assert.throws(()=>validateReplay(v,s,c,1));});
test('minute cannot expose a completed bar at start',()=>{const v=structuredClone(r),snap={...s,bar_size:'1 min'};v.points[0].available_s=v.points[0].coordinate_s;assert.throws(()=>validateReplay(v,snap,c,1));v.points[0].available_s+=60;assert.equal(validateReplay(v,snap,c,1),v);});
test('null warmup never masquerades as zero volatility',()=>{const v=structuredClone(r);v.points[0].rolling[0].annualized_volatility=0;assert.throws(()=>validateReplay(v,s,c,1));});
test('nonfinite value refused',()=>{const v=structuredClone(r);v.points[0].close=Infinity;assert.throws(()=>validateReplay(v,s,c,1));});
test('comparison warns on different datasets',()=>{const a={result:{snapshot_fingerprint:'a',build:{research_source_sha256:'x'}}},b={result:{snapshot_fingerprint:'b',build:{research_source_sha256:'x'}}};assert.match(comparisonLabel(a,b),/Different frozen data/);b.result.snapshot_fingerprint='a';assert.match(comparisonLabel(a,b),/Same frozen/);});
test('saved experiment must contain a validated full run',()=>assert.throws(()=>validateExperiment({immutable:true,retrospective_only:true,engine_version:'retrospective-replay-1',experiment_id:'1',config:c,result:r})));
