import test from 'node:test';
import assert from 'node:assert/strict';
import {validateModel,greekRequest,scenarioRequest,displayGreek,buildLabel,validateGreekRecord} from '../../src/frontend/dashboard/greeks-model.mjs';
const model={exercise_style:'european',right:'call',spot:100,strike:100,maturity_years:1,rate:.05,dividend_yield:0,volatility:.2,currency:'USD'};
const mc={draws:100000,seed:'42',pairing:'plain',estimator:'pathwise',relative_spot_bump:.001,volatility_bump:.001};
const shock={relative_spot:.1,volatility:.01,elapsed_years:0},grid={spot_span:.2,volatility_span:.05};
test('canonical manual model',()=>assert.deepEqual(validateModel(model),model));
test('no American or broker contract input',()=>{assert.throws(()=>validateModel({...model,exercise_style:'american'}));assert.throws(()=>validateModel({...model,contract_id:123}));});
test('nonfinite and negative model inputs rejected',()=>{for(const spot of [-1,Infinity,NaN,null,'100'])assert.throws(()=>validateModel({...model,spot}));});
test('boundaries allowed for price, not silently changed',()=>assert.equal(validateModel({...model,volatility:0}).volatility,0));
test('string uint64 seed remains exact',()=>assert.equal(greekRequest(model,{...mc,seed:'18446744073709551615'}).simulation.seed,'18446744073709551615'));
test('numeric and overflowing seeds rejected',()=>{for(const seed of [42,'18446744073709551616'])assert.throws(()=>greekRequest(model,{...mc,seed}));});
test('pair accounting constraints',()=>{assert.throws(()=>greekRequest(model,{...mc,draws:1001,pairing:'antithetic'}));assert.equal(greekRequest(model,{...mc,pairing:'antithetic'}).simulation.draws,100000);});
test('estimator/bump bounds',()=>{assert.throws(()=>greekRequest(model,{...mc,estimator:'gamma'}));assert.throws(()=>greekRequest(model,{...mc,relative_spot_bump:0}));});
test('CRN lower bump never clamped',()=>assert.throws(()=>greekRequest({...model,volatility:.0001},{...mc,estimator:'central_crn'})));
test('pathwise does not apply inactive bumps',()=>assert.equal(greekRequest({...model,volatility:.0001},mc).simulation.estimator,'pathwise'));
test('display units and null values',()=>{assert.equal(displayGreek(30,'vega'),.3);assert.equal(displayGreek(365,'theta'),1);assert.equal(displayGreek(50,'rho'),.5);assert.equal(displayGreek(.6,'delta'),.6);assert.equal(displayGreek(null,'delta'),null);});
test('selected scenario is explicit',()=>assert.deepEqual(scenarioRequest(model,shock,grid),{schema_version:1,model,shock,grid}));
test('negative volatility selected shock rejected',()=>assert.throws(()=>scenarioRequest(model,{...shock,volatility:-.3},grid)));
test('time roll may reach but not exceed expiry',()=>{assert.equal(scenarioRequest(model,{...shock,elapsed_years:1},grid).shock.elapsed_years,1);assert.throws(()=>scenarioRequest(model,{...shock,elapsed_years:2},grid));});
test('grid width bounded independently',()=>assert.throws(()=>scenarioRequest(model,shock,{...grid,spot_span:.6})));
test('base boundary shock preserves no fabricated Greek',()=>assert.equal(scenarioRequest({...model,volatility:0},shock,grid).model.volatility,0));
test('build badge reports unavailable metadata',()=>{assert.match(buildLabel(null,'none'),/unavailable/);assert.match(buildLabel({git_revision:'fake',source_sha256:'a'.repeat(64)},'none'),/source archive/);});
test('mismatched and forged responses rejected',()=>{assert.throws(()=>validateGreekRecord({},greekRequest(model,mc)));});
