// ✅ Define `endpointMap` outside any function (Global Static)
#include "../../headers/DataStructs/DataStructs.h"

const std::unordered_map<RestAPIQueryType, std::string> firstEndPointMap = {
    {RestAPIQueryType::AGGREGATES, "/v2/aggs/ticker/"},
    {RestAPIQueryType::GROUPEDDAILY, "/v2/aggs/grouped/locale/"},
    {RestAPIQueryType::DAILYOPENCLOSE, "/v1/open-close/"},
    {RestAPIQueryType::PREVIOUSCLOSE, "/v2/aggs/ticker/"},
    {RestAPIQueryType::TRADES, "/v3/trades/"},
    {RestAPIQueryType::LASTTRADE, "/v2/last/trade/"},
    {RestAPIQueryType::LASTTRADECRYPTOPAIR, "/v1/last/crypto/"},
    {RestAPIQueryType::QUOTES, "/v3/quotes/"},
    {RestAPIQueryType::LASTQUOTE, "/v2/last/"},
    {RestAPIQueryType::LASTQUOTECURRENCYPAIR, "/v1/last_quote/currencies/"},
    {RestAPIQueryType::REALTIMECURRENCYCONVERSION, "/v1/conversion/"},
    {RestAPIQueryType::SNAPSHOTSOPTIONCONTRACT, "/v3/snapshot/options/"},
    {RestAPIQueryType::SNAPSHOTSOPTIONCHAIN, "/v3/snapshot/options/"},
    {RestAPIQueryType::SNAPSHOTSUNIVERSALSNAPSHOT, "/v3/snapshot?ticker.any_of="},
    {RestAPIQueryType::SNAPSHOTSALLTICKERS, "/v2/snapshot/locale/"},
    {RestAPIQueryType::SNAPSHOTSGAINERSLOSERS, "/v2/snapshot/locale/"},
    {RestAPIQueryType::SNAPSHOTSTICKER, "/v2/snapshot/locale/"},
    {RestAPIQueryType::SNAPSHOTSUNIVERSALSNAPSHOT, "/v3/snapshot?ticker.any_of="},
    {RestAPIQueryType::TICKERS, "/v3/reference/tickers?active="},
    {RestAPIQueryType::TICKERDETAILSV3, "/v3/reference/tickers/"},
    {RestAPIQueryType::TICKEREVENTS, "/vx/reference/tickers/"},
    {RestAPIQueryType::TICKERNEWS, "/v2/reference/news?limit="},
    {RestAPIQueryType::TICKERTYPES, "/v3/reference/tickers/types?asset_class="},
    {RestAPIQueryType::MARKETHOLIDAYS, "/v1/marketstatus/upcoming?apikey="},
    {RestAPIQueryType::MARKETSTATUS, "/v1/marketstatus/now?apikey="},
    {RestAPIQueryType::STOCKSPLITSV3, "/v3/reference/splits?limit="},
    {RestAPIQueryType::DIVIDENDSV3, "/v3/reference/dividends?limit="},
    {RestAPIQueryType::STOCKFINANCIALSVX, "/vX/reference/financials?limit="},
    {RestAPIQueryType::CONDITIONS, "/v3/reference/conditions?asset_class="},
    {RestAPIQueryType::EXCHANGES, "/v3/reference/exchanges?asset_class="},
    {RestAPIQueryType::RELATEDCOMPANIES, "/v1/related-companies/"},
    {RestAPIQueryType::IPOS, "/vX/reference/ipos?limit="},
    {RestAPIQueryType::OPTIONCONTRACT, "/v3/reference/options/contracts/"},
    {RestAPIQueryType::OPTIONCONTRACTS, "/v3/reference/options/contracts?limit="}
};
