import {makeRequest,parseResult,jobId} from './variation-model.mjs';
export function mountVariation(api,onAccessError){
  const $=id=>document.getElementById(id),text=(id,value)=>{$(id).textContent=value;};
  const node=(tag,value)=>{const n=document.createElement(tag);n.textContent=String(value??'—');return n;};
  const root='/api/variation';let unlocked=false,busy=false,revision=0,timer=null,inputs=[],page=null,current=null,result=null;
  const fmt=v=>typeof v==='number'&&Number.isFinite(v)?v.toExponential(4):'—';
  function controls(){for(const el of $('variation').querySelectorAll('button,input,select'))el.disabled=!unlocked||busy;
    $('var-more').disabled=!unlocked||busy||!page?.has_more;
    $('var-run').disabled=!unlocked||busy||current?.state==='running';
    $('var-cancel').disabled=!unlocked||busy||current?.state!=='running';
    $('var-open').disabled=!unlocked||busy||!$('var-saved').value;
    $('var-export').disabled=$('var-csv').disabled=!unlocked||busy||!result;}
  async function work(fn){if(!unlocked||busy)return;busy=true;const rev=revision;controls();text('var-notice','');try{await fn(rev);}catch(e){if(rev===revision){if([401,403].includes(e.status))onAccessError(e);else text('var-notice',`${e.message} No automatic retry.`);}}finally{if(rev===revision){busy=false;controls();}}}
  function clearResult(){result=null;for(const id of ['var-quality','var-rows','var-scores','var-dates'])$(id).replaceChildren();for(const id of ['var-summary','var-gate','var-conventions','var-evaluation'])text(id,'');draw();}
  function showInputs(){const key=$('var-kind').value==='bars'?'snapshot_id':'session_id';$('var-inputs').replaceChildren(...inputs.map(r=>{const label=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.value=r[key];const date=key==='snapshot_id'?`${new Date(Number(r.start_s)*1000).toISOString().slice(0,16)} UTC window start`:new Date(Number(r.started_ms)).toLocaleString();label.append(c,node('span',`#${r[key]} · ${r.symbol} · ${date} · ${r.name??r.venue} · ${r.source} · ${r.bar_count??r.event_count} ${key==='snapshot_id'?'bars':'events'}`));return label;}));}
  async function loadInputs(rev,more=false){const bars=$('var-kind').value==='bars';const v=await api.request(bars?'/api/research/snapshots/list':'/api/depth/sessions','POST',{after_id:more?page.next_after_id:'0',limit:100});if(rev!==revision)return;
    if(!Array.isArray(v.rows)||v.rows.length>100)throw new Error('Invalid input catalog.');if(!more)inputs=[];
    inputs.push(...v.rows.filter(r=>bars?r.bar_size==='1 min'&&r.price_type==='MIDPOINT'&&r.use_rth:r.state!=='recording'));
    if(inputs.length>1000)throw new Error('Catalog limit reached.');page=v;showInputs();text('var-notice',`${inputs.length} eligible saved inputs listed. Select the same instrument and source conventions.`);}
  $('var-kind').addEventListener('change',()=>{revision++;busy=false;clearTimeout(timer);current=null;text('var-status','');inputs=[];page=null;showInputs();$('var-step').value=$('var-kind').value==='bars'?'60':'5';clearResult();controls();});
  $('var-load').addEventListener('click',()=>work(r=>loadInputs(r)));$('var-more').addEventListener('click',()=>work(r=>loadInputs(r,true)));
  function schedule(){clearTimeout(timer);if(unlocked&&current?.state==='running')timer=setTimeout(()=>work(check),1500);}
  async function check(rev){const v=await api.request(`${root}/jobs/${current.job_id}`);if(rev!==revision)return;current=v;text('var-status',`Study ${v.job_id.slice(0,8)} · ${v.state} · ${v.phase}${v.error?' · '+v.error:''}`);
    if(v.state==='complete'){const output=await api.request(`${root}/jobs/${v.job_id}/result`);if(rev===revision){result=parseResult(output);render();}}
    else schedule();}
  $('var-run').addEventListener('click',()=>work(async rev=>{const kind=$('var-kind').value,key=kind==='bars'?'snapshot_id':'session_id';const selected=new Set([...$('var-inputs').querySelectorAll('input:checked')].map(x=>x.value));const form={input_kind:kind,step_seconds:$('var-step').value,horizon_minutes:$('var-horizon').value,max_side_age_seconds:$('var-age').value,synthetic:$('var-synthetic').checked,compare:$('var-compare').checked};for(const part of ['train','validation','test'])form[part]=$(`var-${part}`).value;
    const request=makeRequest(form,inputs.filter(x=>selected.has(x[key])));const j=await api.request(root+'/jobs','POST',request);if(rev!==revision)return;if(!jobId(j.job_id))throw new Error('Invalid study ID; inspect saved studies before retrying.');clearResult();current=j;text('var-status',`Study ${j.job_id.slice(0,8)} · ${j.state} · freezing saved inputs`);schedule();}));
  $('var-cancel').addEventListener('click',()=>work(async rev=>{await api.request(`${root}/jobs/${current.job_id}/cancel`,'POST',{});if(rev===revision)await check(rev);}));
  $('var-jobs').addEventListener('click',()=>work(async rev=>{const [v,s]=await Promise.all([api.request(root+'/jobs'),api.request(root+'/status')]);if(rev!==revision)return;if(!Array.isArray(v.jobs)||v.jobs.length>50)throw new Error('Invalid study catalog.');$('var-saved').replaceChildren(node('option','Choose a saved study'));$('var-saved').firstChild.value='';for(const j of v.jobs){if(!jobId(j.job_id))throw new Error('Invalid study ID.');const o=node('option',`${new Date(j.created_ms).toLocaleString()} · ${j.input_kind} · ${j.state} · ${j.job_id.slice(0,8)}`);o.value=j.job_id;$('var-saved').append(o);}text('var-notice',`${v.jobs.length} saved studies listed${v.has_more?'; newest 50 shown':''}. ${s.enabled?'Offline worker available.':'Research worker unavailable.'}`);if(s.busy&&jobId(s.active_job_id)){if(current?.job_id!==s.active_job_id)clearResult();current={job_id:s.active_job_id,state:'running'};schedule();}}));
  $('var-saved').addEventListener('change',controls);
  $('var-open').addEventListener('click',()=>work(async rev=>{const id=$('var-saved').value;if(!jobId(id))throw new Error('Select a saved study.');clearTimeout(timer);clearResult();current={job_id:id};await check(rev);}));
  function render(){const v=result;text('var-summary',`${v.identity.symbol} · ${v.request.input_kind==='depth'?'book-derived midpoint':'saved minute midpoint'} · ${v.rows.length} complete ${v.request.configuration.horizon_minutes}-minute windows · ${v.eligible_dates.length} eligible sessions`);
    text('var-gate',v.gate.reason);text('var-conventions',`${v.conventions.candidate} ${v.conventions.distinction} Calendar: ${v.calendar.name} / ${v.calendar.package_version}. ${v.conventions.units}. ${v.limitations.join(' ')}`);
    $('var-quality').replaceChildren(...Object.entries({...v.quality,...v.window_counts}).map(([k,n])=>{const el=document.createElement('article');el.append(node('span',k.replaceAll('_',' ')),node('strong',n));return el;}));
    $('var-dates').replaceChildren(...v.eligible_dates.map(([day,count])=>node('span',`${day}: ${count} windows `)));
    $('var-rows').replaceChildren(...v.rows.slice(-200).map(r=>{const tr=document.createElement('tr');for(const value of [r.date,new Date(r.origin_s*1000).toISOString(),fmt(r.past_bpv),fmt(r.future_rv),fmt(r.future_bpv),fmt(r.future_rv_minus_bpv),fmt(r.future_candidate_excess),r.spread_bps==null?'—':r.spread_bps.toFixed(3),r.visible_depth??'—'])tr.append(node('td',value));return tr;}));
    const e=v.evaluation;text('var-evaluation',`${e.status.replaceAll('_',' ')}. ${e.reason??e.selection??''} ${e.uncertainty??''}`);
    $('var-scores').replaceChildren(...Object.entries(e.models??{}).map(([name,m])=>{const tr=document.createElement('tr');for(const x of [name,fmt(m.test.equal_day_mse),fmt(m.test.equal_day_qlike),m.clipped_test_forecasts??0])tr.append(node('td',x));return tr;}));draw();controls();}
  function draw(){const canvas=$('var-chart'),box=canvas.getBoundingClientRect();if(!box.width)return;const ratio=devicePixelRatio||1;canvas.width=box.width*ratio;canvas.height=260*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.font='12px system-ui';ctx.fillStyle='#9caaa9';
    const rows=result?.rows??[];if(!rows.length){ctx.fillText('No eligible variation windows',15,35);canvas.setAttribute('aria-label','No eligible variation windows');return;}
    const step=Math.max(1,Math.ceil(rows.length/1500)),points=rows.filter((_,i)=>i%step===0||i===rows.length-1);let max=0;for(const r of points)max=Math.max(max,r.future_rv,r.future_bpv);max=max||1;const width=box.width-105;
    for(const [key,color] of [['future_rv','#7fc9b2'],['future_bpv','#dfac8a']]){ctx.strokeStyle=color;ctx.beginPath();points.forEach((r,i)=>{const x=12+i/Math.max(1,points.length-1)*width,y=215-r[key]/max*180;if(!i||r.date!==points[i-1].date||r.origin_s>points[i-1].target_end_s+1)ctx.moveTo(x,y);else ctx.lineTo(x,y);ctx.fillStyle=color;ctx.fillRect(x-2,y-2,4,4);});ctx.stroke();}
    ctx.fillStyle='#9caaa9';ctx.fillText(`RV: green · BPV: orange${step>1?' · display sampled':''}`,12,18);ctx.fillText(fmt(max),width+20,40);ctx.fillText('0',width+20,220);ctx.fillText(points[0].date,12,248);ctx.textAlign='right';ctx.fillText(points.at(-1).date,width+12,248);ctx.textAlign='left';canvas.setAttribute('aria-label',`${rows.length} measured RV and BPV windows; full values available in export.`);}
  new ResizeObserver(draw).observe($('var-chart'));
  function download(body,type,name){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  $('var-export').addEventListener('click',()=>download(JSON.stringify(result,null,2),'application/json',`variation-${current.job_id}.json`));
  $('var-csv').addEventListener('click',()=>{const keys=['date','origin_s','target_end_s','past_bpv','past_rv','future_rv','future_bpv','future_rv_minus_bpv','future_candidate_excess','spread_bps','visible_depth','trailing_ofi'];download([keys.join(','),...result.rows.map(r=>keys.map(k=>r[k]??'').join(','))].join('\n'),'text/csv',`variation-${current.job_id}.csv`);});
  controls();return {setAccess(v){if(unlocked===v)return;unlocked=v;revision++;busy=false;clearTimeout(timer);if(!v){inputs=[];page=current=null;clearResult();$('var-inputs').replaceChildren();$('var-saved').replaceChildren();for(const k of ['var-status','var-notice','var-evaluation'])text(k,'');for(const k of ['train','validation','test'])$(`var-${k}`).value='';}controls();}};
}
