# Self-contained dashboard: no CDN, Node build, runtime path, or generated secrets.
set(DTS_DASHBOARD_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src/frontend/dashboard")
set(DTS_DASHBOARD_HEADER "#pragma once\nnamespace dts::dashboard::assets {\n")
foreach(asset index.html dashboard.css app.mjs model.mjs pricing.mjs pricing-model.mjs)
    set(path "${DTS_DASHBOARD_DIR}/${asset}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
    file(READ "${path}" content)
    string(FIND "${content}" ")DTS_ASSET\"" delimiter)
    if(NOT delimiter EQUAL -1)
        message(FATAL_ERROR "Dashboard asset collides with raw-string delimiter: ${asset}")
    endif()
    string(REPLACE "." "_" symbol "${asset}")
    string(REPLACE "-" "_" symbol "${symbol}")
    string(APPEND DTS_DASHBOARD_HEADER "inline constexpr char ${symbol}[] = R\"DTS_ASSET(${content})DTS_ASSET\";\n")
endforeach()
string(APPEND DTS_DASHBOARD_HEADER "}\n")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/generated/dts_dashboard_assets.hpp" "${DTS_DASHBOARD_HEADER}")
target_include_directories(server PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/generated" "${CMAKE_CURRENT_SOURCE_DIR}/src/backend/cpp_src/http")
