# Supply a separately downloaded official API 10.45.01 IBJts directory.
# Do not redistribute the SDK in this repository or mutate the user's SDK copy.
if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "The native adapter currently targets Linux/WSL")
endif()
set(IBKR_API_ROOT "" CACHE PATH "Official IBJts SDK directory (tested: 10.45.01)")
if(NOT EXISTS "${IBKR_API_ROOT}/source/cppclient/client/EClientSocket.h")
    message(FATAL_ERROR "Set IBKR_API_ROOT to the downloaded official IBJts directory")
endif()
find_package(Protobuf REQUIRED)
find_package(Threads REQUIRED)
find_library(IBKR_BID_LIBRARY NAMES bidgcc000 bid)
if(NOT IBKR_BID_LIBRARY)
    message(FATAL_ERROR "Install libintelrdfpmath-dev or set IBKR_BID_LIBRARY to the ABI-compatible Intel BID library (CALL_BY_REF=0 GLOBAL_RND=0 GLOBAL_FLAGS=0)")
endif()
set(IBKR_STAGED "${CMAKE_CURRENT_BINARY_DIR}/ibkr-sdk/client")
file(MAKE_DIRECTORY "${IBKR_STAGED}")
file(COPY "${IBKR_API_ROOT}/source/cppclient/client/" DESTINATION "${IBKR_STAGED}")
# Regenerate with the installed protoc to match libprotobuf; do not compile
# the SDK's pre-generated protobuf against an incompatible system runtime.
file(GLOB IBKR_PROTOS "${IBKR_API_ROOT}/source/proto/*.proto")
if(NOT IBKR_PROTOS)
    message(FATAL_ERROR "Missing official IBKR protobuf schemas")
endif()
execute_process(COMMAND "${Protobuf_PROTOC_EXECUTABLE}"
    "--proto_path=${IBKR_API_ROOT}/source/proto"
    "--cpp_out=${IBKR_STAGED}/protobufUnix" ${IBKR_PROTOS}
    RESULT_VARIABLE PROTO_RESULT ERROR_VARIABLE PROTO_ERROR)
if(NOT PROTO_RESULT EQUAL 0)
    message(FATAL_ERROR "IBKR protobuf generation failed: ${PROTO_ERROR}")
endif()
file(GLOB IBKR_CPP "${IBKR_STAGED}/*.cpp" "${IBKR_STAGED}/protobufUnix/*.cc")
add_library(ibkr_sdk STATIC ${IBKR_CPP})
target_compile_features(ibkr_sdk PUBLIC cxx_std_17)
target_include_directories(ibkr_sdk SYSTEM PUBLIC "${IBKR_STAGED}" "${IBKR_STAGED}/protobufUnix")
target_link_libraries(ibkr_sdk PUBLIC protobuf::libprotobuf Threads::Threads ${IBKR_BID_LIBRARY} ${CMAKE_DL_LIBS})
add_library(trading_ibkr STATIC src/backend/cpp_src/ibkr/tws_broker.cpp)
target_link_libraries(trading_ibkr PUBLIC trading_core PRIVATE ibkr_sdk)
target_compile_options(trading_ibkr PRIVATE -Wall -Wextra -Wpedantic -Werror)
add_executable(tws_probe apps/tws_probe.cpp)
configure_executable(tws_probe)
target_link_libraries(tws_probe PRIVATE trading_ibkr)
if(BUILD_TESTING)
    add_executable(tws_callback_tests tests/tws_callback_tests.cpp)
    configure_executable(tws_callback_tests)
    target_include_directories(tws_callback_tests PRIVATE src/backend/cpp_src/ibkr)
    target_link_libraries(tws_callback_tests PRIVATE ibkr_sdk)
    add_test(NAME tws_callback_tests COMMAND tws_callback_tests)
    find_package(Python3 COMPONENTS Interpreter REQUIRED)
    add_test(NAME tws_transport_tests COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/tws_transport_tests.py" "$<TARGET_FILE:tws_probe>")
    set_tests_properties(tws_transport_tests PROPERTIES TIMEOUT 25)
endif()
